# netlify.toml

[build]
  # This tells Netlify where your serverless functions are.
  # Make sure your 'youtubeproxy.js' file is inside a folder named 'netlify/functions'
  functions = "netlify/functions"

[functions]
  # It's good practice to specify the Node.js version for consistency.
  node_bundler = "esbuild"

[[redirects]]
  from = "/video"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/playlist"
  to = "/index.html"
  status = 200
